/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ElN: typeof import('element-plus/es')['ElN']
  const ElNo: typeof import('element-plus/es')['ElNo']
  const ElNotification: typeof import('element-plus/es')['ElNotification']
}
